services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Client:
        decorates: RM\Component\Client\Transport\TransportInterface
    RM\Component\Client\ClientInterface: '@RM\Component\Client\Client'
    RM\Component\Client\RepositoryRegistryInterface: '@RM\Component\Client\Client'
