services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Client: null
    RM\Component\Client\ClientInterface:
        public: true
        alias: RM\Component\Client\Client
