services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Repository\RepositoryRegistryInterface:
        public: true
        alias: RM\Component\Client\Repository\RepositoryRegistry
    RM\Component\Client\Repository\RepositoryRegistry: null

    RM\Component\Client\Repository\RepositoryFactoryInterface:
        alias: RM\Bundle\ClientBundle\Repository\ServiceRepositoryFactory
    RM\Bundle\ClientBundle\Repository\ServiceRepositoryFactory:
        arguments:
            $container: !tagged_locator
                tag: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_REPOSITORY

    _instanceof:
        RM\Component\Client\Repository\RepositoryInterface:
            public: true
            tags:
                - { name: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_REPOSITORY }

    RM\Component\Client\Repository\UserRepository: null
    RM\Component\Client\Repository\ApplicationRepository: null
