services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Security\Storage\TokenStorageInterface:
        alias: RM\Bundle\ClientBundle\Security\Storage\SessionTokenStorage
    RM\Bundle\ClientBundle\Security\Storage\SessionTokenStorage:

    RM\Component\Client\Security\Authenticator\AuthenticatorFactoryInterface:
        alias: RM\Bundle\ClientBundle\Security\Authenticator\ServiceAuthenticatorFactory
    RM\Bundle\ClientBundle\Security\Authenticator\ServiceAuthenticatorFactory:
        arguments:
            $container: !tagged_locator
                tag: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_AUTHENTICATOR

    _instanceof:
        RM\Component\Client\Security\Authenticator\AuthenticatorInterface:
            tags:
                - { name: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_AUTHENTICATOR }
