services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Transport\ThrowableTransport:
        decorates: RM\Component\Client\Transport\TransportInterface
    RM\Component\Client\Transport\HttpTransport: null
