services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Security\Authenticator\Factory\AuthenticatorFactoryInterface:
        alias: RM\Bundle\ClientBundle\Security\Authenticator\Factory\ServiceAuthenticatorFactory
    RM\Bundle\ClientBundle\Security\Authenticator\Factory\ServiceAuthenticatorFactory:
        arguments:
            $container: !tagged_locator
                tag: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_AUTHENTICATOR
    RM\Component\Client\Security\Authenticator\Factory\AliasedAuthenticatorFactory:
        decorates: RM\Bundle\ClientBundle\Security\Authenticator\Factory\ServiceAuthenticatorFactory

    _instanceof:
        RM\Component\Client\Security\Authenticator\AuthenticatorInterface:
            tags:
                - { name: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_AUTHENTICATOR }
        RM\Component\Client\Security\Authenticator\RedirectAuthenticatorInterface:
            calls:
                -   setFactory: ['@RM\Component\Client\Security\Authenticator\Factory\AuthenticatorFactoryInterface']
        RM\Component\Client\Security\Authenticator\StorableAuthenticatorInterface:
            calls:
                -   setStorage: ['@RM\Component\Client\Security\Storage\AuthorizationStorageInterface']

    RM\Component\Client\Security\Authenticator\ServiceAuthenticator: null
    RM\Component\Client\Security\Authenticator\CodeAuthenticator: null
    RM\Component\Client\Security\Authenticator\SignInAuthenticator: null
