services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Hydrator\HydratorInterface:
        alias: RM\Component\Client\Hydrator\EntityHydrator
    RM\Component\Client\Hydrator\EntityHydrator: null

    RM\Component\Client\Hydrator\EventfulHydrator:
        decorates: RM\Component\Client\Hydrator\HydratorInterface
