services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    RM\Component\Client\Repository\Registry\RepositoryRegistryInterface:
        public: true
        alias: RM\Component\Client\Repository\Registry\RepositoryRegistry
    RM\Component\Client\Repository\Registry\RepositoryRegistry: null

    RM\Component\Client\Repository\Factory\RepositoryFactoryInterface:
        alias: RM\Bundle\ClientBundle\Repository\ServiceRepositoryFactory
    RM\Bundle\ClientBundle\Repository\ServiceRepositoryFactory: null

    _instanceof:
        RM\Component\Client\Repository\RepositoryInterface:
            public: true
            tags:
                - name: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_REPOSITORY

    RM\Bundle\ClientBundle\Repository\UserRepository:
        tags:
            - name: !php/const RM\Bundle\ClientBundle\RelmsgClientBundle::TAG_REPOSITORY
              alias: RM\Component\Client\Repository\UserRepository
    RM\Component\Client\Repository\ApplicationRepository: null
