services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    _instanceof:
        RM\Component\Client\Transport\TransportInterface:
            calls:
                -   setResolver: ['@RM\Component\Client\Security\Resolver\AuthorizationResolverInterface']

    RM\Component\Client\Transport\HttpTransport: null
